// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	Categories        string
	ProductCategories string
	Products          string
	SchemaMigrations  string
}{
	Categories:        "categories",
	ProductCategories: "product_categories",
	Products:          "products",
	SchemaMigrations:  "schema_migrations",
}
