// Code generated by mockery v2.20.0. DO NOT EDIT.

package repository

import (
	inventory "github.com/kytruong0712/getgo/api/internal/repository/inventory"
	mock "github.com/stretchr/testify/mock"
)

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

// Inventory provides a mock function with given fields:
func (_m *MockRegistry) Inventory() inventory.Repository {
	ret := _m.Called()

	var r0 inventory.Repository
	if rf, ok := ret.Get(0).(func() inventory.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(inventory.Repository)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockRegistry interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRegistry(t mockConstructorTestingTNewMockRegistry) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
