// Code generated by mockery v2.20.0. DO NOT EDIT.

package authentication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *MockController) Login(_a0 context.Context, _a1 LoginInput) (TokenOutput, string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 TokenOutput
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, LoginInput) (TokenOutput, string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, LoginInput) TokenOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(TokenOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, LoginInput) string); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, LoginInput) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewMockController interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockController(t mockConstructorTestingTNewMockController) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
