// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CharacterInput struct {
	Name string  `json:"name"`
	ID   *string `json:"id,omitempty"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Age      int    `json:"age"`
}

type UpdateUserInput struct {
	ID         string `json:"id"`
	Externalid string `json:"externalid"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	Email      string `json:"email"`
	Age        int    `json:"age"`
}

type User struct {
	ID         string `json:"id"`
	Externalid string `json:"externalid"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	Email      string `json:"email"`
	Age        int    `json:"age"`
}
